//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.08.27 at 11:20:40 PM EDT 
//

package com.es.manager.common;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;

import com.es.manager.property.design.PrimaryBusinessType;

/**
 * <p>
 * Java class for organizationType complex type.
 * 
 * <p>
 * The following schema fragment specifies the expected content contained within
 * this class.
 * 
 * <pre>
 * &lt;complexType name="organizationType"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;all&gt;
 *         &lt;element name="primaryBusiness" type="{}primaryBusinessType"/&gt;
 *         &lt;element name="otherBusinessDescription" minOccurs="0"&gt;
 *           &lt;simpleType&gt;
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string"&gt;
 *               &lt;minLength value="1"/&gt;
 *               &lt;maxLength value="1000"/&gt;
 *             &lt;/restriction&gt;
 *           &lt;/simpleType&gt;
 *         &lt;/element&gt;
 *         &lt;element name="energyStarPartner" type="{http://www.w3.org/2001/XMLSchema}boolean"/&gt;
 *         &lt;element name="energyStarPartnerType" type="{}typeOfEnergyStarPartner" minOccurs="0"/&gt;
 *         &lt;element name="otherPartnerDescription" minOccurs="0"&gt;
 *           &lt;simpleType&gt;
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string"&gt;
 *               &lt;minLength value="1"/&gt;
 *               &lt;maxLength value="100"/&gt;
 *             &lt;/restriction&gt;
 *           &lt;/simpleType&gt;
 *         &lt;/element&gt;
 *       &lt;/all&gt;
 *       &lt;attribute name="name"&gt;
 *         &lt;simpleType&gt;
 *           &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string"&gt;
 *             &lt;minLength value="1"/&gt;
 *             &lt;maxLength value="1000"/&gt;
 *           &lt;/restriction&gt;
 *         &lt;/simpleType&gt;
 *       &lt;/attribute&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "organizationType", propOrder = {

})
public class OrganizationType {

	@XmlElement(required = true)
	@XmlSchemaType(name = "string")
	protected PrimaryBusinessType primaryBusiness;
	protected String otherBusinessDescription;
	protected boolean energyStarPartner;
	@XmlSchemaType(name = "string")
	protected TypeOfEnergyStarPartner energyStarPartnerType;
	protected String otherPartnerDescription;
	@XmlAttribute(name = "name")
	protected String name;

	/**
	 * Gets the value of the primaryBusiness property.
	 * 
	 * @return possible object is {@link PrimaryBusinessType }
	 * 
	 */
	public PrimaryBusinessType getPrimaryBusiness() {
		return primaryBusiness;
	}

	/**
	 * Sets the value of the primaryBusiness property.
	 * 
	 * @param value
	 *            allowed object is {@link PrimaryBusinessType }
	 * 
	 */
	public void setPrimaryBusiness(PrimaryBusinessType value) {
		this.primaryBusiness = value;
	}

	/**
	 * Gets the value of the otherBusinessDescription property.
	 * 
	 * @return possible object is {@link String }
	 * 
	 */
	public String getOtherBusinessDescription() {
		return otherBusinessDescription;
	}

	/**
	 * Sets the value of the otherBusinessDescription property.
	 * 
	 * @param value
	 *            allowed object is {@link String }
	 * 
	 */
	public void setOtherBusinessDescription(String value) {
		this.otherBusinessDescription = value;
	}

	/**
	 * Gets the value of the energyStarPartner property.
	 * 
	 */
	public boolean isEnergyStarPartner() {
		return energyStarPartner;
	}

	/**
	 * Sets the value of the energyStarPartner property.
	 * 
	 */
	public void setEnergyStarPartner(boolean value) {
		this.energyStarPartner = value;
	}

	/**
	 * Gets the value of the energyStarPartnerType property.
	 * 
	 * @return possible object is {@link TypeOfEnergyStarPartner }
	 * 
	 */
	public TypeOfEnergyStarPartner getEnergyStarPartnerType() {
		return energyStarPartnerType;
	}

	/**
	 * Sets the value of the energyStarPartnerType property.
	 * 
	 * @param value
	 *            allowed object is {@link TypeOfEnergyStarPartner }
	 * 
	 */
	public void setEnergyStarPartnerType(TypeOfEnergyStarPartner value) {
		this.energyStarPartnerType = value;
	}

	/**
	 * Gets the value of the otherPartnerDescription property.
	 * 
	 * @return possible object is {@link String }
	 * 
	 */
	public String getOtherPartnerDescription() {
		return otherPartnerDescription;
	}

	/**
	 * Sets the value of the otherPartnerDescription property.
	 * 
	 * @param value
	 *            allowed object is {@link String }
	 * 
	 */
	public void setOtherPartnerDescription(String value) {
		this.otherPartnerDescription = value;
	}

	/**
	 * Gets the value of the name property.
	 * 
	 * @return possible object is {@link String }
	 * 
	 */
	public String getName() {
		return name;
	}

	/**
	 * Sets the value of the name property.
	 * 
	 * @param value
	 *            allowed object is {@link String }
	 * 
	 */
	public void setName(String value) {
		this.name = value;
	}

	@Override
	public String toString() {
		return "OrganizationType [primaryBusiness=" + primaryBusiness + ", otherBusinessDescription="
				+ otherBusinessDescription + ", energyStarPartner=" + energyStarPartner + ", energyStarPartnerType="
				+ energyStarPartnerType + ", otherPartnerDescription=" + otherPartnerDescription + ", name=" + name
				+ "]";
	}

}
