//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.08.27 at 11:20:40 PM EDT 
//


package com.es.manager.common;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for questionType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="questionType"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;attribute name="id" use="required"&gt;
 *         &lt;simpleType&gt;
 *           &lt;restriction base="{http://www.w3.org/2001/XMLSchema}long"&gt;
 *             &lt;enumeration value="-1"/&gt;
 *             &lt;enumeration value="-2"/&gt;
 *             &lt;enumeration value="-3"/&gt;
 *             &lt;enumeration value="-4"/&gt;
 *             &lt;enumeration value="-5"/&gt;
 *             &lt;enumeration value="-6"/&gt;
 *             &lt;enumeration value="-7"/&gt;
 *             &lt;enumeration value="-8"/&gt;
 *             &lt;enumeration value="-9"/&gt;
 *             &lt;enumeration value="-10"/&gt;
 *             &lt;enumeration value="-11"/&gt;
 *             &lt;enumeration value="-12"/&gt;
 *             &lt;enumeration value="-13"/&gt;
 *             &lt;enumeration value="-14"/&gt;
 *             &lt;enumeration value="-15"/&gt;
 *             &lt;enumeration value="-16"/&gt;
 *             &lt;enumeration value="-17"/&gt;
 *             &lt;enumeration value="-18"/&gt;
 *           &lt;/restriction&gt;
 *         &lt;/simpleType&gt;
 *       &lt;/attribute&gt;
 *       &lt;attribute name="text" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "questionType")
public class QuestionType {

    @XmlAttribute(name = "id", required = true)
    protected long id;
    @XmlAttribute(name = "text")
    protected String text;

    /**
     * Gets the value of the id property.
     * 
     */
    public long getId() {
        return id;
    }

    /**
     * Sets the value of the id property.
     * 
     */
    public void setId(long value) {
        this.id = value;
    }

    /**
     * Gets the value of the text property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getText() {
        return text;
    }

    /**
     * Sets the value of the text property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setText(String value) {
        this.text = value;
    }

	@Override
	public String toString() {
		return "QuestionType [id=" + id + ", text=" + text + "]";
	}
    
    

}
