//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.08.28 at 12:33:18 AM EDT 
//


package com.es.manager.property.metrics;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for baselineAndTargetType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="baselineAndTargetType"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="baseline" type="{}baselineType" minOccurs="0"/&gt;
 *         &lt;element name="target" type="{}performanceTargetType" minOccurs="0"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "baselineAndTargetType", propOrder = {
    "baseline",
    "target"
})
@XmlRootElement(name="baselineAndTarget")
public class BaselineAndTargetType {

    protected BaselineType baseline;
    protected PerformanceTargetType target;

    /**
     * Gets the value of the baseline property.
     * 
     * @return
     *     possible object is
     *     {@link BaselineType }
     *     
     */
    public BaselineType getBaseline() {
        return baseline;
    }

    /**
     * Sets the value of the baseline property.
     * 
     * @param value
     *     allowed object is
     *     {@link BaselineType }
     *     
     */
    public void setBaseline(BaselineType value) {
        this.baseline = value;
    }

    /**
     * Gets the value of the target property.
     * 
     * @return
     *     possible object is
     *     {@link PerformanceTargetType }
     *     
     */
    public PerformanceTargetType getTarget() {
        return target;
    }

    /**
     * Sets the value of the target property.
     * 
     * @param value
     *     allowed object is
     *     {@link PerformanceTargetType }
     *     
     */
    public void setTarget(PerformanceTargetType value) {
        this.target = value;
    }

}
