//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.08.28 at 12:33:18 AM EDT 
//


package com.es.manager.property.metrics;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for baselineType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="baselineType"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="energyBaselineDate" type="{}baselineDateType" minOccurs="0"/&gt;
 *         &lt;element name="waterBaselineDate" type="{}baselineDateType" minOccurs="0"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "baselineType", propOrder = {
    "energyBaselineDate",
    "waterBaselineDate"
})
public class BaselineType {

    @XmlSchemaType(name = "anySimpleType")
    protected String energyBaselineDate;
    @XmlSchemaType(name = "anySimpleType")
    protected String waterBaselineDate;

    /**
     * Gets the value of the energyBaselineDate property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getEnergyBaselineDate() {
        return energyBaselineDate;
    }

    /**
     * Sets the value of the energyBaselineDate property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setEnergyBaselineDate(String value) {
        this.energyBaselineDate = value;
    }

    /**
     * Gets the value of the waterBaselineDate property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getWaterBaselineDate() {
        return waterBaselineDate;
    }

    /**
     * Sets the value of the waterBaselineDate property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setWaterBaselineDate(String value) {
        this.waterBaselineDate = value;
    }

}
