//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.08.28 at 12:21:55 AM EDT 
//


package com.es.manager.meter;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlEnumValue;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for typeOfMeter.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="typeOfMeter"&gt;
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string"&gt;
 *     &lt;enumeration value="Coal Anthracite"/&gt;
 *     &lt;enumeration value="Coal Bituminous"/&gt;
 *     &lt;enumeration value="Coke"/&gt;
 *     &lt;enumeration value="Diesel"/&gt;
 *     &lt;enumeration value="District Chilled Water - Absorption Chiller using Natural Gas"/&gt;
 *     &lt;enumeration value="District Chilled Water - Electric-Driven Chiller"/&gt;
 *     &lt;enumeration value="District Chilled Water - Engine-Driven Chiller using Natural Gas"/&gt;
 *     &lt;enumeration value="District Chilled Water - Other"/&gt;
 *     &lt;enumeration value="District Hot Water"/&gt;
 *     &lt;enumeration value="District Steam"/&gt;
 *     &lt;enumeration value="Electric"/&gt;
 *     &lt;enumeration value="Electric on Site Solar"/&gt;
 *     &lt;enumeration value="Electric on Site Wind"/&gt;
 *     &lt;enumeration value="Fuel Oil No 1"/&gt;
 *     &lt;enumeration value="Fuel Oil No 2"/&gt;
 *     &lt;enumeration value="Fuel Oil No 4"/&gt;
 *     &lt;enumeration value="Fuel Oil No 5 or 6"/&gt;
 *     &lt;enumeration value="Kerosene"/&gt;
 *     &lt;enumeration value="Natural Gas"/&gt;
 *     &lt;enumeration value="Other (Energy)"/&gt;
 *     &lt;enumeration value="Propane"/&gt;
 *     &lt;enumeration value="Wood"/&gt;
 *     &lt;enumeration value="IT Equipment Input Energy (meters on each piece of equipment)"/&gt;
 *     &lt;enumeration value="Power Distribution Unit (PDU) Input Energy"/&gt;
 *     &lt;enumeration value="Power Distribution Unit (PDU) Output Energy"/&gt;
 *     &lt;enumeration value="Uninterruptible Power Supply (UPS) Output Energy"/&gt;
 *     &lt;enumeration value="Alternative Water Generated On-Site - All"/&gt;
 *     &lt;enumeration value="Alternative Water Generated On-Site - Indoor"/&gt;
 *     &lt;enumeration value="Alternative Water Generated On-Site - Outdoor"/&gt;
 *     &lt;enumeration value="Municipally Supplied Potable Water - All"/&gt;
 *     &lt;enumeration value="Municipally Supplied Potable Water - Indoor"/&gt;
 *     &lt;enumeration value="Municipally Supplied Potable Water - Outdoor"/&gt;
 *     &lt;enumeration value="Municipally Supplied Reclaimed Water - All"/&gt;
 *     &lt;enumeration value="Municipally Supplied Reclaimed Water - Indoor"/&gt;
 *     &lt;enumeration value="Municipally Supplied Reclaimed Water - Outdoor"/&gt;
 *     &lt;enumeration value="Other - All (Water)"/&gt;
 *     &lt;enumeration value="Other - Outdoor"/&gt;
 *     &lt;enumeration value="Other - Indoor"/&gt;
 *     &lt;enumeration value="Average Influent Flow"/&gt;
 *   &lt;/restriction&gt;
 * &lt;/simpleType&gt;
 * </pre>
 * 
 */
@XmlType(name = "typeOfMeter")
@XmlEnum
public enum TypeOfMeter {

    @XmlEnumValue("Coal Anthracite")
    COAL_ANTHRACITE("Coal Anthracite"),
    @XmlEnumValue("Coal Bituminous")
    COAL_BITUMINOUS("Coal Bituminous"),
    @XmlEnumValue("Coke")
    COKE("Coke"),
    @XmlEnumValue("Diesel")
    DIESEL("Diesel"),
    @XmlEnumValue("District Chilled Water - Absorption Chiller using Natural Gas")
    DISTRICT_CHILLED_WATER_ABSORPTION_CHILLER_USING_NATURAL_GAS("District Chilled Water - Absorption Chiller using Natural Gas"),
    @XmlEnumValue("District Chilled Water - Electric-Driven Chiller")
    DISTRICT_CHILLED_WATER_ELECTRIC_DRIVEN_CHILLER("District Chilled Water - Electric-Driven Chiller"),
    @XmlEnumValue("District Chilled Water - Engine-Driven Chiller using Natural Gas")
    DISTRICT_CHILLED_WATER_ENGINE_DRIVEN_CHILLER_USING_NATURAL_GAS("District Chilled Water - Engine-Driven Chiller using Natural Gas"),
    @XmlEnumValue("District Chilled Water - Other")
    DISTRICT_CHILLED_WATER_OTHER("District Chilled Water - Other"),
    @XmlEnumValue("District Hot Water")
    DISTRICT_HOT_WATER("District Hot Water"),
    @XmlEnumValue("District Steam")
    DISTRICT_STEAM("District Steam"),
    @XmlEnumValue("Electric")
    ELECTRIC("Electric"),
    @XmlEnumValue("Electric on Site Solar")
    ELECTRIC_ON_SITE_SOLAR("Electric on Site Solar"),
    @XmlEnumValue("Electric on Site Wind")
    ELECTRIC_ON_SITE_WIND("Electric on Site Wind"),
    @XmlEnumValue("Fuel Oil No 1")
    FUEL_OIL_NO_1("Fuel Oil No 1"),
    @XmlEnumValue("Fuel Oil No 2")
    FUEL_OIL_NO_2("Fuel Oil No 2"),
    @XmlEnumValue("Fuel Oil No 4")
    FUEL_OIL_NO_4("Fuel Oil No 4"),
    @XmlEnumValue("Fuel Oil No 5 or 6")
    FUEL_OIL_NO_5_OR_6("Fuel Oil No 5 or 6"),
    @XmlEnumValue("Kerosene")
    KEROSENE("Kerosene"),
    @XmlEnumValue("Natural Gas")
    NATURAL_GAS("Natural Gas"),
    @XmlEnumValue("Other (Energy)")
    OTHER_ENERGY("Other (Energy)"),
    @XmlEnumValue("Propane")
    PROPANE("Propane"),
    @XmlEnumValue("Wood")
    WOOD("Wood"),
    @XmlEnumValue("IT Equipment Input Energy (meters on each piece of equipment)")
    IT_EQUIPMENT_INPUT_ENERGY_METERS_ON_EACH_PIECE_OF_EQUIPMENT("IT Equipment Input Energy (meters on each piece of equipment)"),
    @XmlEnumValue("Power Distribution Unit (PDU) Input Energy")
    POWER_DISTRIBUTION_UNIT_PDU_INPUT_ENERGY("Power Distribution Unit (PDU) Input Energy"),
    @XmlEnumValue("Power Distribution Unit (PDU) Output Energy")
    POWER_DISTRIBUTION_UNIT_PDU_OUTPUT_ENERGY("Power Distribution Unit (PDU) Output Energy"),
    @XmlEnumValue("Uninterruptible Power Supply (UPS) Output Energy")
    UNINTERRUPTIBLE_POWER_SUPPLY_UPS_OUTPUT_ENERGY("Uninterruptible Power Supply (UPS) Output Energy"),
    @XmlEnumValue("Alternative Water Generated On-Site - All")
    ALTERNATIVE_WATER_GENERATED_ON_SITE_ALL("Alternative Water Generated On-Site - All"),
    @XmlEnumValue("Alternative Water Generated On-Site - Indoor")
    ALTERNATIVE_WATER_GENERATED_ON_SITE_INDOOR("Alternative Water Generated On-Site - Indoor"),
    @XmlEnumValue("Alternative Water Generated On-Site - Outdoor")
    ALTERNATIVE_WATER_GENERATED_ON_SITE_OUTDOOR("Alternative Water Generated On-Site - Outdoor"),
    @XmlEnumValue("Municipally Supplied Potable Water - All")
    MUNICIPALLY_SUPPLIED_POTABLE_WATER_ALL("Municipally Supplied Potable Water - All"),
    @XmlEnumValue("Municipally Supplied Potable Water - Indoor")
    MUNICIPALLY_SUPPLIED_POTABLE_WATER_INDOOR("Municipally Supplied Potable Water - Indoor"),
    @XmlEnumValue("Municipally Supplied Potable Water - Outdoor")
    MUNICIPALLY_SUPPLIED_POTABLE_WATER_OUTDOOR("Municipally Supplied Potable Water - Outdoor"),
    @XmlEnumValue("Municipally Supplied Reclaimed Water - All")
    MUNICIPALLY_SUPPLIED_RECLAIMED_WATER_ALL("Municipally Supplied Reclaimed Water - All"),
    @XmlEnumValue("Municipally Supplied Reclaimed Water - Indoor")
    MUNICIPALLY_SUPPLIED_RECLAIMED_WATER_INDOOR("Municipally Supplied Reclaimed Water - Indoor"),
    @XmlEnumValue("Municipally Supplied Reclaimed Water - Outdoor")
    MUNICIPALLY_SUPPLIED_RECLAIMED_WATER_OUTDOOR("Municipally Supplied Reclaimed Water - Outdoor"),
    @XmlEnumValue("Other - All (Water)")
    OTHER_ALL_WATER("Other - All (Water)"),
    @XmlEnumValue("Other - Outdoor")
    OTHER_OUTDOOR("Other - Outdoor"),
    @XmlEnumValue("Other - Indoor")
    OTHER_INDOOR("Other - Indoor"),
    @XmlEnumValue("Average Influent Flow")
    AVERAGE_INFLUENT_FLOW("Average Influent Flow");
    private final String value;

    TypeOfMeter(String v) {
        value = v;
    }

    public String value() {
        return value;
    }

    public static TypeOfMeter fromValue(String v) {
        for (TypeOfMeter c: TypeOfMeter.values()) {
            if (c.value.equals(v)) {
                return c;
            }
        }
        throw new IllegalArgumentException(v);
    }

}
