//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.08.28 at 12:35:27 AM EDT 
//


package com.es.manager.property.design;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;

import com.es.manager.common.LogType;


/**
 * <p>Java class for dataCenterType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="dataCenterType"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;all&gt;
 *         &lt;element name="name" type="{}propertyUseNameType"/&gt;
 *         &lt;element name="useDetails"&gt;
 *           &lt;complexType&gt;
 *             &lt;complexContent&gt;
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *                 &lt;all&gt;
 *                   &lt;element ref="{}totalGrossFloorArea"/&gt;
 *                   &lt;element ref="{}coolingEquipmentRedundancy" minOccurs="0"/&gt;
 *                   &lt;element ref="{}itEnergyMeterConfiguration" minOccurs="0"/&gt;
 *                   &lt;element ref="{}upsSystemRedundancy" minOccurs="0"/&gt;
 *                 &lt;/all&gt;
 *               &lt;/restriction&gt;
 *             &lt;/complexContent&gt;
 *           &lt;/complexType&gt;
 *         &lt;/element&gt;
 *         &lt;element name="audit" type="{}logType" minOccurs="0"/&gt;
 *       &lt;/all&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "dataCenterType", propOrder = {

})
@XmlRootElement(name="dataCenter")
public class DataCenterType extends BasePropertyUseType{

    @XmlElement(required = true)
    protected String name;
    @XmlElement(required = true)
    protected DataCenterType.UseDetails useDetails;
    protected LogType audit;

    /**
     * Gets the value of the name property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getName() {
        return name;
    }

    /**
     * Sets the value of the name property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setName(String value) {
        this.name = value;
    }

    /**
     * Gets the value of the useDetails property.
     * 
     * @return
     *     possible object is
     *     {@link DataCenterType.UseDetails }
     *     
     */
    public DataCenterType.UseDetails getUseDetails() {
        return useDetails;
    }

    /**
     * Sets the value of the useDetails property.
     * 
     * @param value
     *     allowed object is
     *     {@link DataCenterType.UseDetails }
     *     
     */
    public void setUseDetails(DataCenterType.UseDetails value) {
        this.useDetails = value;
    }

    /**
     * Gets the value of the audit property.
     * 
     * @return
     *     possible object is
     *     {@link LogType }
     *     
     */
    public LogType getAudit() {
        return audit;
    }

    /**
     * Sets the value of the audit property.
     * 
     * @param value
     *     allowed object is
     *     {@link LogType }
     *     
     */
    public void setAudit(LogType value) {
        this.audit = value;
    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType&gt;
     *   &lt;complexContent&gt;
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
     *       &lt;all&gt;
     *         &lt;element ref="{}totalGrossFloorArea"/&gt;
     *         &lt;element ref="{}coolingEquipmentRedundancy" minOccurs="0"/&gt;
     *         &lt;element ref="{}itEnergyMeterConfiguration" minOccurs="0"/&gt;
     *         &lt;element ref="{}upsSystemRedundancy" minOccurs="0"/&gt;
     *       &lt;/all&gt;
     *     &lt;/restriction&gt;
     *   &lt;/complexContent&gt;
     * &lt;/complexType&gt;
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {

    })
    public static class UseDetails {

        @XmlElement(required = true)
        protected GrossFloorAreaType totalGrossFloorArea;
        protected CoolingEquipmentRedundancyType coolingEquipmentRedundancy;
        protected ItEnergyConfigurationType itEnergyMeterConfiguration;
        protected UpsSystemRedundancyType upsSystemRedundancy;

        /**
         * Gets the value of the totalGrossFloorArea property.
         * 
         * @return
         *     possible object is
         *     {@link GrossFloorAreaType }
         *     
         */
        public GrossFloorAreaType getTotalGrossFloorArea() {
            return totalGrossFloorArea;
        }

        /**
         * Sets the value of the totalGrossFloorArea property.
         * 
         * @param value
         *     allowed object is
         *     {@link GrossFloorAreaType }
         *     
         */
        public void setTotalGrossFloorArea(GrossFloorAreaType value) {
            this.totalGrossFloorArea = value;
        }

        /**
         * Gets the value of the coolingEquipmentRedundancy property.
         * 
         * @return
         *     possible object is
         *     {@link CoolingEquipmentRedundancyType }
         *     
         */
        public CoolingEquipmentRedundancyType getCoolingEquipmentRedundancy() {
            return coolingEquipmentRedundancy;
        }

        /**
         * Sets the value of the coolingEquipmentRedundancy property.
         * 
         * @param value
         *     allowed object is
         *     {@link CoolingEquipmentRedundancyType }
         *     
         */
        public void setCoolingEquipmentRedundancy(CoolingEquipmentRedundancyType value) {
            this.coolingEquipmentRedundancy = value;
        }

        /**
         * Gets the value of the itEnergyMeterConfiguration property.
         * 
         * @return
         *     possible object is
         *     {@link ItEnergyConfigurationType }
         *     
         */
        public ItEnergyConfigurationType getItEnergyMeterConfiguration() {
            return itEnergyMeterConfiguration;
        }

        /**
         * Sets the value of the itEnergyMeterConfiguration property.
         * 
         * @param value
         *     allowed object is
         *     {@link ItEnergyConfigurationType }
         *     
         */
        public void setItEnergyMeterConfiguration(ItEnergyConfigurationType value) {
            this.itEnergyMeterConfiguration = value;
        }

        /**
         * Gets the value of the upsSystemRedundancy property.
         * 
         * @return
         *     possible object is
         *     {@link UpsSystemRedundancyType }
         *     
         */
        public UpsSystemRedundancyType getUpsSystemRedundancy() {
            return upsSystemRedundancy;
        }

        /**
         * Sets the value of the upsSystemRedundancy property.
         * 
         * @param value
         *     allowed object is
         *     {@link UpsSystemRedundancyType }
         *     
         */
        public void setUpsSystemRedundancy(UpsSystemRedundancyType value) {
            this.upsSystemRedundancy = value;
        }

    }

}
