//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.08.28 at 12:35:27 AM EDT 
//


package com.es.manager.property.design;

import java.math.BigDecimal;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for estimatedEnergyType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="estimatedEnergyType"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;all&gt;
 *         &lt;element name="energyType" type="{}allEnergyMetersType"/&gt;
 *         &lt;element name="energyUnit" type="{}designUnitOfMeasure"/&gt;
 *         &lt;element name="estimatedAnnualEnergyUsage" type="{http://www.w3.org/2001/XMLSchema}long"/&gt;
 *         &lt;element name="energyRateCost" type="{http://www.w3.org/2001/XMLSchema}decimal" minOccurs="0"/&gt;
 *         &lt;element name="energyRateCostUnit" type="{}designUnitOfMeasure" minOccurs="0"/&gt;
 *       &lt;/all&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "estimatedEnergyType", propOrder = {

})
public class EstimatedEnergyType {

    @XmlElement(required = true)
    @XmlSchemaType(name = "string")
    protected AllEnergyMetersType energyType;
    @XmlElement(required = true)
    @XmlSchemaType(name = "string")
    protected DesignUnitOfMeasure energyUnit;
    protected long estimatedAnnualEnergyUsage;
    protected BigDecimal energyRateCost;
    @XmlSchemaType(name = "string")
    protected DesignUnitOfMeasure energyRateCostUnit;

    /**
     * Gets the value of the energyType property.
     * 
     * @return
     *     possible object is
     *     {@link AllEnergyMetersType }
     *     
     */
    public AllEnergyMetersType getEnergyType() {
        return energyType;
    }

    /**
     * Sets the value of the energyType property.
     * 
     * @param value
     *     allowed object is
     *     {@link AllEnergyMetersType }
     *     
     */
    public void setEnergyType(AllEnergyMetersType value) {
        this.energyType = value;
    }

    /**
     * Gets the value of the energyUnit property.
     * 
     * @return
     *     possible object is
     *     {@link DesignUnitOfMeasure }
     *     
     */
    public DesignUnitOfMeasure getEnergyUnit() {
        return energyUnit;
    }

    /**
     * Sets the value of the energyUnit property.
     * 
     * @param value
     *     allowed object is
     *     {@link DesignUnitOfMeasure }
     *     
     */
    public void setEnergyUnit(DesignUnitOfMeasure value) {
        this.energyUnit = value;
    }

    /**
     * Gets the value of the estimatedAnnualEnergyUsage property.
     * 
     */
    public long getEstimatedAnnualEnergyUsage() {
        return estimatedAnnualEnergyUsage;
    }

    /**
     * Sets the value of the estimatedAnnualEnergyUsage property.
     * 
     */
    public void setEstimatedAnnualEnergyUsage(long value) {
        this.estimatedAnnualEnergyUsage = value;
    }

    /**
     * Gets the value of the energyRateCost property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getEnergyRateCost() {
        return energyRateCost;
    }

    /**
     * Sets the value of the energyRateCost property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setEnergyRateCost(BigDecimal value) {
        this.energyRateCost = value;
    }

    /**
     * Gets the value of the energyRateCostUnit property.
     * 
     * @return
     *     possible object is
     *     {@link DesignUnitOfMeasure }
     *     
     */
    public DesignUnitOfMeasure getEnergyRateCostUnit() {
        return energyRateCostUnit;
    }

    /**
     * Sets the value of the energyRateCostUnit property.
     * 
     * @param value
     *     allowed object is
     *     {@link DesignUnitOfMeasure }
     *     
     */
    public void setEnergyRateCostUnit(DesignUnitOfMeasure value) {
        this.energyRateCostUnit = value;
    }

}
