//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.08.28 at 12:35:27 AM EDT 
//


package com.es.manager.property.design;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.bind.annotation.XmlType;

import com.es.manager.property.use.UseAttributeBase;


/**
 * <p>Java class for floorAreaTypeBase complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="floorAreaTypeBase"&gt;
 *   &lt;complexContent&gt;
 *     &lt;extension base="{}useAttributeBase"&gt;
 *       &lt;attribute name="units" use="required" type="{}grossFloorAreaUnitsType" /&gt;
 *     &lt;/extension&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "floorAreaTypeBase")
@XmlSeeAlso({
    GrossFloorAreaType.class,
    OptionalFloorAreaType.class
})
public class FloorAreaTypeBase
    extends UseAttributeBase
{

    @XmlAttribute(name = "units", required = true)
    protected GrossFloorAreaUnitsType units;

    /**
     * Gets the value of the units property.
     * 
     * @return
     *     possible object is
     *     {@link GrossFloorAreaUnitsType }
     *     
     */
    public GrossFloorAreaUnitsType getUnits() {
        return units;
    }

    /**
     * Sets the value of the units property.
     * 
     * @param value
     *     allowed object is
     *     {@link GrossFloorAreaUnitsType }
     *     
     */
    public void setUnits(GrossFloorAreaUnitsType value) {
        this.units = value;
    }

}
