//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.08.28 at 12:35:27 AM EDT 
//


package com.es.manager.property.design;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;

import com.es.manager.common.LogType;
import com.es.manager.property.use.UseDecimalType;
import com.es.manager.property.use.UseIntegerType;
import com.es.manager.property.use.UseYesNoType;


/**
 * <p>Java class for indoorArenaType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="indoorArenaType"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;all&gt;
 *         &lt;element name="name" type="{}propertyUseNameType"/&gt;
 *         &lt;element name="useDetails"&gt;
 *           &lt;complexType&gt;
 *             &lt;complexContent&gt;
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *                 &lt;all&gt;
 *                   &lt;element ref="{}totalGrossFloorArea"/&gt;
 *                   &lt;element ref="{}enclosedFloorArea" minOccurs="0"/&gt;
 *                   &lt;element ref="{}numberOfSportingEventsPerYear" minOccurs="0"/&gt;
 *                   &lt;element ref="{}numberOfConcertShowEventsPerYear" minOccurs="0"/&gt;
 *                   &lt;element ref="{}numberOfSpecialOtherEventsPerYear" minOccurs="0"/&gt;
 *                   &lt;element ref="{}sizeOfElectronicScoreBoards" minOccurs="0"/&gt;
 *                   &lt;element ref="{}iceEvents" minOccurs="0"/&gt;
 *                   &lt;element ref="{}numberOfComputers" minOccurs="0"/&gt;
 *                   &lt;element ref="{}numberOfWalkInRefrigerationUnits" minOccurs="0"/&gt;
 *                   &lt;element ref="{}percentCooled" minOccurs="0"/&gt;
 *                   &lt;element ref="{}percentHeated" minOccurs="0"/&gt;
 *                 &lt;/all&gt;
 *               &lt;/restriction&gt;
 *             &lt;/complexContent&gt;
 *           &lt;/complexType&gt;
 *         &lt;/element&gt;
 *         &lt;element name="audit" type="{}logType" minOccurs="0"/&gt;
 *       &lt;/all&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "indoorArenaType", propOrder = {

})
@XmlRootElement(name="indoorArena")
public class IndoorArenaType {

    @XmlElement(required = true)
    protected String name;
    @XmlElement(required = true)
    protected IndoorArenaType.UseDetails useDetails;
    protected LogType audit;

    /**
     * Gets the value of the name property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getName() {
        return name;
    }

    /**
     * Sets the value of the name property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setName(String value) {
        this.name = value;
    }

    /**
     * Gets the value of the useDetails property.
     * 
     * @return
     *     possible object is
     *     {@link IndoorArenaType.UseDetails }
     *     
     */
    public IndoorArenaType.UseDetails getUseDetails() {
        return useDetails;
    }

    /**
     * Sets the value of the useDetails property.
     * 
     * @param value
     *     allowed object is
     *     {@link IndoorArenaType.UseDetails }
     *     
     */
    public void setUseDetails(IndoorArenaType.UseDetails value) {
        this.useDetails = value;
    }

    /**
     * Gets the value of the audit property.
     * 
     * @return
     *     possible object is
     *     {@link LogType }
     *     
     */
    public LogType getAudit() {
        return audit;
    }

    /**
     * Sets the value of the audit property.
     * 
     * @param value
     *     allowed object is
     *     {@link LogType }
     *     
     */
    public void setAudit(LogType value) {
        this.audit = value;
    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType&gt;
     *   &lt;complexContent&gt;
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
     *       &lt;all&gt;
     *         &lt;element ref="{}totalGrossFloorArea"/&gt;
     *         &lt;element ref="{}enclosedFloorArea" minOccurs="0"/&gt;
     *         &lt;element ref="{}numberOfSportingEventsPerYear" minOccurs="0"/&gt;
     *         &lt;element ref="{}numberOfConcertShowEventsPerYear" minOccurs="0"/&gt;
     *         &lt;element ref="{}numberOfSpecialOtherEventsPerYear" minOccurs="0"/&gt;
     *         &lt;element ref="{}sizeOfElectronicScoreBoards" minOccurs="0"/&gt;
     *         &lt;element ref="{}iceEvents" minOccurs="0"/&gt;
     *         &lt;element ref="{}numberOfComputers" minOccurs="0"/&gt;
     *         &lt;element ref="{}numberOfWalkInRefrigerationUnits" minOccurs="0"/&gt;
     *         &lt;element ref="{}percentCooled" minOccurs="0"/&gt;
     *         &lt;element ref="{}percentHeated" minOccurs="0"/&gt;
     *       &lt;/all&gt;
     *     &lt;/restriction&gt;
     *   &lt;/complexContent&gt;
     * &lt;/complexType&gt;
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {

    })
    public static class UseDetails {

        @XmlElement(required = true)
        protected GrossFloorAreaType totalGrossFloorArea;
        protected OptionalFloorAreaType enclosedFloorArea;
        protected UseIntegerType numberOfSportingEventsPerYear;
        protected UseIntegerType numberOfConcertShowEventsPerYear;
        protected UseIntegerType numberOfSpecialOtherEventsPerYear;
        protected OptionalFloorAreaType sizeOfElectronicScoreBoards;
        protected UseYesNoType iceEvents;
        protected UseDecimalType numberOfComputers;
        protected UseDecimalType numberOfWalkInRefrigerationUnits;
        protected PercentCooledType percentCooled;
        protected PercentHeatedType percentHeated;

        /**
         * Gets the value of the totalGrossFloorArea property.
         * 
         * @return
         *     possible object is
         *     {@link GrossFloorAreaType }
         *     
         */
        public GrossFloorAreaType getTotalGrossFloorArea() {
            return totalGrossFloorArea;
        }

        /**
         * Sets the value of the totalGrossFloorArea property.
         * 
         * @param value
         *     allowed object is
         *     {@link GrossFloorAreaType }
         *     
         */
        public void setTotalGrossFloorArea(GrossFloorAreaType value) {
            this.totalGrossFloorArea = value;
        }

        /**
         * Gets the value of the enclosedFloorArea property.
         * 
         * @return
         *     possible object is
         *     {@link OptionalFloorAreaType }
         *     
         */
        public OptionalFloorAreaType getEnclosedFloorArea() {
            return enclosedFloorArea;
        }

        /**
         * Sets the value of the enclosedFloorArea property.
         * 
         * @param value
         *     allowed object is
         *     {@link OptionalFloorAreaType }
         *     
         */
        public void setEnclosedFloorArea(OptionalFloorAreaType value) {
            this.enclosedFloorArea = value;
        }

        /**
         * Gets the value of the numberOfSportingEventsPerYear property.
         * 
         * @return
         *     possible object is
         *     {@link UseIntegerType }
         *     
         */
        public UseIntegerType getNumberOfSportingEventsPerYear() {
            return numberOfSportingEventsPerYear;
        }

        /**
         * Sets the value of the numberOfSportingEventsPerYear property.
         * 
         * @param value
         *     allowed object is
         *     {@link UseIntegerType }
         *     
         */
        public void setNumberOfSportingEventsPerYear(UseIntegerType value) {
            this.numberOfSportingEventsPerYear = value;
        }

        /**
         * Gets the value of the numberOfConcertShowEventsPerYear property.
         * 
         * @return
         *     possible object is
         *     {@link UseIntegerType }
         *     
         */
        public UseIntegerType getNumberOfConcertShowEventsPerYear() {
            return numberOfConcertShowEventsPerYear;
        }

        /**
         * Sets the value of the numberOfConcertShowEventsPerYear property.
         * 
         * @param value
         *     allowed object is
         *     {@link UseIntegerType }
         *     
         */
        public void setNumberOfConcertShowEventsPerYear(UseIntegerType value) {
            this.numberOfConcertShowEventsPerYear = value;
        }

        /**
         * Gets the value of the numberOfSpecialOtherEventsPerYear property.
         * 
         * @return
         *     possible object is
         *     {@link UseIntegerType }
         *     
         */
        public UseIntegerType getNumberOfSpecialOtherEventsPerYear() {
            return numberOfSpecialOtherEventsPerYear;
        }

        /**
         * Sets the value of the numberOfSpecialOtherEventsPerYear property.
         * 
         * @param value
         *     allowed object is
         *     {@link UseIntegerType }
         *     
         */
        public void setNumberOfSpecialOtherEventsPerYear(UseIntegerType value) {
            this.numberOfSpecialOtherEventsPerYear = value;
        }

        /**
         * Gets the value of the sizeOfElectronicScoreBoards property.
         * 
         * @return
         *     possible object is
         *     {@link OptionalFloorAreaType }
         *     
         */
        public OptionalFloorAreaType getSizeOfElectronicScoreBoards() {
            return sizeOfElectronicScoreBoards;
        }

        /**
         * Sets the value of the sizeOfElectronicScoreBoards property.
         * 
         * @param value
         *     allowed object is
         *     {@link OptionalFloorAreaType }
         *     
         */
        public void setSizeOfElectronicScoreBoards(OptionalFloorAreaType value) {
            this.sizeOfElectronicScoreBoards = value;
        }

        /**
         * Gets the value of the iceEvents property.
         * 
         * @return
         *     possible object is
         *     {@link UseYesNoType }
         *     
         */
        public UseYesNoType getIceEvents() {
            return iceEvents;
        }

        /**
         * Sets the value of the iceEvents property.
         * 
         * @param value
         *     allowed object is
         *     {@link UseYesNoType }
         *     
         */
        public void setIceEvents(UseYesNoType value) {
            this.iceEvents = value;
        }

        /**
         * Gets the value of the numberOfComputers property.
         * 
         * @return
         *     possible object is
         *     {@link UseDecimalType }
         *     
         */
        public UseDecimalType getNumberOfComputers() {
            return numberOfComputers;
        }

        /**
         * Sets the value of the numberOfComputers property.
         * 
         * @param value
         *     allowed object is
         *     {@link UseDecimalType }
         *     
         */
        public void setNumberOfComputers(UseDecimalType value) {
            this.numberOfComputers = value;
        }

        /**
         * Gets the value of the numberOfWalkInRefrigerationUnits property.
         * 
         * @return
         *     possible object is
         *     {@link UseDecimalType }
         *     
         */
        public UseDecimalType getNumberOfWalkInRefrigerationUnits() {
            return numberOfWalkInRefrigerationUnits;
        }

        /**
         * Sets the value of the numberOfWalkInRefrigerationUnits property.
         * 
         * @param value
         *     allowed object is
         *     {@link UseDecimalType }
         *     
         */
        public void setNumberOfWalkInRefrigerationUnits(UseDecimalType value) {
            this.numberOfWalkInRefrigerationUnits = value;
        }

        /**
         * Gets the value of the percentCooled property.
         * 
         * @return
         *     possible object is
         *     {@link PercentCooledType }
         *     
         */
        public PercentCooledType getPercentCooled() {
            return percentCooled;
        }

        /**
         * Sets the value of the percentCooled property.
         * 
         * @param value
         *     allowed object is
         *     {@link PercentCooledType }
         *     
         */
        public void setPercentCooled(PercentCooledType value) {
            this.percentCooled = value;
        }

        /**
         * Gets the value of the percentHeated property.
         * 
         * @return
         *     possible object is
         *     {@link PercentHeatedType }
         *     
         */
        public PercentHeatedType getPercentHeated() {
            return percentHeated;
        }

        /**
         * Sets the value of the percentHeated property.
         * 
         * @param value
         *     allowed object is
         *     {@link PercentHeatedType }
         *     
         */
        public void setPercentHeated(PercentHeatedType value) {
            this.percentHeated = value;
        }

    }

}
