//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.08.28 at 12:35:27 AM EDT 
//


package com.es.manager.property.design;

import java.math.BigDecimal;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;

import com.es.manager.property.design.LengthUnitsType;
import com.es.manager.property.use.UseAttributeBase;


/**
 * <p>Java class for lengthOfAllOpenClosedRefrigerationUnitsType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="lengthOfAllOpenClosedRefrigerationUnitsType"&gt;
 *   &lt;complexContent&gt;
 *     &lt;extension base="{}useAttributeBase"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="value" type="{http://www.w3.org/2001/XMLSchema}decimal" minOccurs="0"/&gt;
 *       &lt;/sequence&gt;
 *       &lt;attribute name="units" use="required" type="{}lengthUnitsType" /&gt;
 *     &lt;/extension&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "lengthOfAllOpenClosedRefrigerationUnitsType", propOrder = {
    "value"
})
@XmlRootElement(name="lengthOfAllOpenClosedRefrigerationUnits")
public class LengthOfAllOpenClosedRefrigerationUnitsType
    extends UseAttributeBase
{

    protected BigDecimal value;
    @XmlAttribute(name = "units", required = true)
    protected LengthUnitsType units;

    /**
     * Gets the value of the value property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getValue() {
        return value;
    }

    /**
     * Sets the value of the value property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setValue(BigDecimal value) {
        this.value = value;
    }

    /**
     * Gets the value of the units property.
     * 
     * @return
     *     possible object is
     *     {@link LengthUnitsType }
     *     
     */
    public LengthUnitsType getUnits() {
        return units;
    }

    /**
     * Sets the value of the units property.
     * 
     * @param value
     *     allowed object is
     *     {@link LengthUnitsType }
     *     
     */
    public void setUnits(LengthUnitsType value) {
        this.units = value;
    }

}
