//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.08.28 at 12:35:27 AM EDT 
//


package com.es.manager.property.design;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;

import com.es.manager.common.LogType;
import com.es.manager.property.use.UseYesNoType;


/**
 * <p>Java class for parkingType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="parkingType"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;all&gt;
 *         &lt;element name="name" type="{}propertyUseNameType"/&gt;
 *         &lt;element name="useDetails"&gt;
 *           &lt;complexType&gt;
 *             &lt;complexContent&gt;
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *                 &lt;all&gt;
 *                   &lt;element ref="{}supplementalHeating" minOccurs="0"/&gt;
 *                   &lt;element ref="{}openFootage"/&gt;
 *                   &lt;element ref="{}completelyEnclosedFootage"/&gt;
 *                   &lt;element ref="{}partiallyEnclosedFootage"/&gt;
 *                 &lt;/all&gt;
 *               &lt;/restriction&gt;
 *             &lt;/complexContent&gt;
 *           &lt;/complexType&gt;
 *         &lt;/element&gt;
 *         &lt;element name="audit" type="{}logType" minOccurs="0"/&gt;
 *       &lt;/all&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "parkingType", propOrder = {

})
@XmlRootElement(name="parking")
public class ParkingType extends BasePropertyUseType{

    @XmlElement(required = true)
    protected String name;
    @XmlElement(required = true)
    protected ParkingType.UseDetails useDetails;
    protected LogType audit;

    /**
     * Gets the value of the name property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getName() {
        return name;
    }

    /**
     * Sets the value of the name property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setName(String value) {
        this.name = value;
    }

    /**
     * Gets the value of the useDetails property.
     * 
     * @return
     *     possible object is
     *     {@link ParkingType.UseDetails }
     *     
     */
    public ParkingType.UseDetails getUseDetails() {
        return useDetails;
    }

    /**
     * Sets the value of the useDetails property.
     * 
     * @param value
     *     allowed object is
     *     {@link ParkingType.UseDetails }
     *     
     */
    public void setUseDetails(ParkingType.UseDetails value) {
        this.useDetails = value;
    }

    /**
     * Gets the value of the audit property.
     * 
     * @return
     *     possible object is
     *     {@link LogType }
     *     
     */
    public LogType getAudit() {
        return audit;
    }

    /**
     * Sets the value of the audit property.
     * 
     * @param value
     *     allowed object is
     *     {@link LogType }
     *     
     */
    public void setAudit(LogType value) {
        this.audit = value;
    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType&gt;
     *   &lt;complexContent&gt;
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
     *       &lt;all&gt;
     *         &lt;element ref="{}supplementalHeating" minOccurs="0"/&gt;
     *         &lt;element ref="{}openFootage"/&gt;
     *         &lt;element ref="{}completelyEnclosedFootage"/&gt;
     *         &lt;element ref="{}partiallyEnclosedFootage"/&gt;
     *       &lt;/all&gt;
     *     &lt;/restriction&gt;
     *   &lt;/complexContent&gt;
     * &lt;/complexType&gt;
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {

    })
    public static class UseDetails {

        protected UseYesNoType supplementalHeating;
        @XmlElement(required = true)
        protected GrossFloorAreaType openFootage;
        @XmlElement(required = true)
        protected GrossFloorAreaType completelyEnclosedFootage;
        @XmlElement(required = true)
        protected GrossFloorAreaType partiallyEnclosedFootage;

        /**
         * Gets the value of the supplementalHeating property.
         * 
         * @return
         *     possible object is
         *     {@link UseYesNoType }
         *     
         */
        public UseYesNoType getSupplementalHeating() {
            return supplementalHeating;
        }

        /**
         * Sets the value of the supplementalHeating property.
         * 
         * @param value
         *     allowed object is
         *     {@link UseYesNoType }
         *     
         */
        public void setSupplementalHeating(UseYesNoType value) {
            this.supplementalHeating = value;
        }

        /**
         * Gets the value of the openFootage property.
         * 
         * @return
         *     possible object is
         *     {@link GrossFloorAreaType }
         *     
         */
        public GrossFloorAreaType getOpenFootage() {
            return openFootage;
        }

        /**
         * Sets the value of the openFootage property.
         * 
         * @param value
         *     allowed object is
         *     {@link GrossFloorAreaType }
         *     
         */
        public void setOpenFootage(GrossFloorAreaType value) {
            this.openFootage = value;
        }

        /**
         * Gets the value of the completelyEnclosedFootage property.
         * 
         * @return
         *     possible object is
         *     {@link GrossFloorAreaType }
         *     
         */
        public GrossFloorAreaType getCompletelyEnclosedFootage() {
            return completelyEnclosedFootage;
        }

        /**
         * Sets the value of the completelyEnclosedFootage property.
         * 
         * @param value
         *     allowed object is
         *     {@link GrossFloorAreaType }
         *     
         */
        public void setCompletelyEnclosedFootage(GrossFloorAreaType value) {
            this.completelyEnclosedFootage = value;
        }

        /**
         * Gets the value of the partiallyEnclosedFootage property.
         * 
         * @return
         *     possible object is
         *     {@link GrossFloorAreaType }
         *     
         */
        public GrossFloorAreaType getPartiallyEnclosedFootage() {
            return partiallyEnclosedFootage;
        }

        /**
         * Sets the value of the partiallyEnclosedFootage property.
         * 
         * @param value
         *     allowed object is
         *     {@link GrossFloorAreaType }
         *     
         */
        public void setPartiallyEnclosedFootage(GrossFloorAreaType value) {
            this.partiallyEnclosedFootage = value;
        }

    }

}
