//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.08.28 at 12:35:27 AM EDT 
//


package com.es.manager.property.design;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlType;

import com.es.manager.common.LinksType;


/**
 * <p>Java class for pendingListType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="pendingListType"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="account" type="{}pendingAccountsType" maxOccurs="unbounded" minOccurs="0"/&gt;
 *         &lt;element name="property" type="{}pendingPropertiesType" maxOccurs="unbounded" minOccurs="0"/&gt;
 *         &lt;element name="meter" type="{}pendingMetersType" maxOccurs="unbounded" minOccurs="0"/&gt;
 *         &lt;element name="links" type="{}linksType" minOccurs="0"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "pendingListType", propOrder = {
    "account",
    "property",
    "meter",
    "links"
})
public class PendingListType {

    protected List<PendingAccountsType> account;
    protected List<PendingPropertiesType> property;
    protected List<PendingMetersType> meter;
    protected LinksType links;

    /**
     * Gets the value of the account property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the account property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getAccount().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link PendingAccountsType }
     * 
     * 
     */
    public List<PendingAccountsType> getAccount() {
        if (account == null) {
            account = new ArrayList<PendingAccountsType>();
        }
        return this.account;
    }

    /**
     * Gets the value of the property property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the property property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getProperty().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link PendingPropertiesType }
     * 
     * 
     */
    public List<PendingPropertiesType> getProperty() {
        if (property == null) {
            property = new ArrayList<PendingPropertiesType>();
        }
        return this.property;
    }

    /**
     * Gets the value of the meter property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the meter property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getMeter().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link PendingMetersType }
     * 
     * 
     */
    public List<PendingMetersType> getMeter() {
        if (meter == null) {
            meter = new ArrayList<PendingMetersType>();
        }
        return this.meter;
    }

    /**
     * Gets the value of the links property.
     * 
     * @return
     *     possible object is
     *     {@link LinksType }
     *     
     */
    public LinksType getLinks() {
        return links;
    }

    /**
     * Sets the value of the links property.
     * 
     * @param value
     *     allowed object is
     *     {@link LinksType }
     *     
     */
    public void setLinks(LinksType value) {
        this.links = value;
    }

}
