//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.08.28 at 12:35:27 AM EDT 
//


package com.es.manager.property.design;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlEnumValue;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for PlantDesignFlowRateUnitsType.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="PlantDesignFlowRateUnitsType"&gt;
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string"&gt;
 *     &lt;enumeration value="Million Gallons per Day"/&gt;
 *     &lt;enumeration value="Cubic Meters per Day"/&gt;
 *   &lt;/restriction&gt;
 * &lt;/simpleType&gt;
 * </pre>
 * 
 */
@XmlType(name = "PlantDesignFlowRateUnitsType")
@XmlEnum
public enum PlantDesignFlowRateUnitsType {

    @XmlEnumValue("Million Gallons per Day")
    MILLION_GALLONS_PER_DAY("Million Gallons per Day"),
    @XmlEnumValue("Cubic Meters per Day")
    CUBIC_METERS_PER_DAY("Cubic Meters per Day");
    private final String value;

    PlantDesignFlowRateUnitsType(String v) {
        value = v;
    }

    public String value() {
        return value;
    }

    public static PlantDesignFlowRateUnitsType fromValue(String v) {
        for (PlantDesignFlowRateUnitsType c: PlantDesignFlowRateUnitsType.values()) {
            if (c.value.equals(v)) {
                return c;
            }
        }
        throw new IllegalArgumentException(v);
    }

}
