//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.08.28 at 12:35:27 AM EDT 
//


package com.es.manager.property.design;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;

import com.es.manager.common.AddressType;


/**
 * <p>Java class for propertyDesignType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="propertyDesignType"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;all&gt;
 *         &lt;element name="name"&gt;
 *           &lt;simpleType&gt;
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string"&gt;
 *               &lt;minLength value="1"/&gt;
 *               &lt;maxLength value="80"/&gt;
 *             &lt;/restriction&gt;
 *           &lt;/simpleType&gt;
 *         &lt;/element&gt;
 *         &lt;element name="primaryFunction" type="{}primaryFunctionType"/&gt;
 *         &lt;element name="grossFloorArea" type="{}grossFloorAreaType"/&gt;
 *         &lt;element name="plannedConstructionCompletionYear" type="{http://www.w3.org/2001/XMLSchema}int"/&gt;
 *         &lt;element name="address" type="{}addressType"/&gt;
 *         &lt;element name="numberOfBuildings"&gt;
 *           &lt;simpleType&gt;
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}int"&gt;
 *               &lt;minInclusive value="0"/&gt;
 *             &lt;/restriction&gt;
 *           &lt;/simpleType&gt;
 *         &lt;/element&gt;
 *       &lt;/all&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "propertyDesignType", propOrder = {

})
public class PropertyDesignType {

    @XmlElement(required = true)
    protected String name;
    @XmlElement(required = true)
    @XmlSchemaType(name = "string")
    protected PrimaryFunctionType primaryFunction;
    @XmlElement(required = true)
    protected GrossFloorAreaType grossFloorArea;
    protected int plannedConstructionCompletionYear;
    @XmlElement(required = true)
    protected AddressType address;
    protected int numberOfBuildings;

    /**
     * Gets the value of the name property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getName() {
        return name;
    }

    /**
     * Sets the value of the name property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setName(String value) {
        this.name = value;
    }

    /**
     * Gets the value of the primaryFunction property.
     * 
     * @return
     *     possible object is
     *     {@link PrimaryFunctionType }
     *     
     */
    public PrimaryFunctionType getPrimaryFunction() {
        return primaryFunction;
    }

    /**
     * Sets the value of the primaryFunction property.
     * 
     * @param value
     *     allowed object is
     *     {@link PrimaryFunctionType }
     *     
     */
    public void setPrimaryFunction(PrimaryFunctionType value) {
        this.primaryFunction = value;
    }

    /**
     * Gets the value of the grossFloorArea property.
     * 
     * @return
     *     possible object is
     *     {@link GrossFloorAreaType }
     *     
     */
    public GrossFloorAreaType getGrossFloorArea() {
        return grossFloorArea;
    }

    /**
     * Sets the value of the grossFloorArea property.
     * 
     * @param value
     *     allowed object is
     *     {@link GrossFloorAreaType }
     *     
     */
    public void setGrossFloorArea(GrossFloorAreaType value) {
        this.grossFloorArea = value;
    }

    /**
     * Gets the value of the plannedConstructionCompletionYear property.
     * 
     */
    public int getPlannedConstructionCompletionYear() {
        return plannedConstructionCompletionYear;
    }

    /**
     * Sets the value of the plannedConstructionCompletionYear property.
     * 
     */
    public void setPlannedConstructionCompletionYear(int value) {
        this.plannedConstructionCompletionYear = value;
    }

    /**
     * Gets the value of the address property.
     * 
     * @return
     *     possible object is
     *     {@link AddressType }
     *     
     */
    public AddressType getAddress() {
        return address;
    }

    /**
     * Sets the value of the address property.
     * 
     * @param value
     *     allowed object is
     *     {@link AddressType }
     *     
     */
    public void setAddress(AddressType value) {
        this.address = value;
    }

    /**
     * Gets the value of the numberOfBuildings property.
     * 
     */
    public int getNumberOfBuildings() {
        return numberOfBuildings;
    }

    /**
     * Sets the value of the numberOfBuildings property.
     * 
     */
    public void setNumberOfBuildings(int value) {
        this.numberOfBuildings = value;
    }

}
