//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.08.27 at 11:59:11 PM EDT 
//


package com.es.manager.association;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for meterPropertyAssociationListType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="meterPropertyAssociationListType"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;all&gt;
 *         &lt;element name="energyMeterAssociation" type="{}energyMeterAssocAndConfigType" minOccurs="0"/&gt;
 *         &lt;element name="waterMeterAssociation" type="{}waterMeterAssocAndConfigType" minOccurs="0"/&gt;
 *       &lt;/all&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "meterPropertyAssociationListType", propOrder = {

})
@XmlRootElement(name="meterPropertyAssociationList")
public class MeterPropertyAssociationListType {

    protected EnergyMeterAssocAndConfigType energyMeterAssociation;
    protected WaterMeterAssocAndConfigType waterMeterAssociation;

    /**
     * Gets the value of the energyMeterAssociation property.
     * 
     * @return
     *     possible object is
     *     {@link EnergyMeterAssocAndConfigType }
     *     
     */
    public EnergyMeterAssocAndConfigType getEnergyMeterAssociation() {
        return energyMeterAssociation;
    }

    /**
     * Sets the value of the energyMeterAssociation property.
     * 
     * @param value
     *     allowed object is
     *     {@link EnergyMeterAssocAndConfigType }
     *     
     */
    public void setEnergyMeterAssociation(EnergyMeterAssocAndConfigType value) {
        this.energyMeterAssociation = value;
    }

    /**
     * Gets the value of the waterMeterAssociation property.
     * 
     * @return
     *     possible object is
     *     {@link WaterMeterAssocAndConfigType }
     *     
     */
    public WaterMeterAssocAndConfigType getWaterMeterAssociation() {
        return waterMeterAssociation;
    }

    /**
     * Sets the value of the waterMeterAssociation property.
     * 
     * @param value
     *     allowed object is
     *     {@link WaterMeterAssocAndConfigType }
     *     
     */
    public void setWaterMeterAssociation(WaterMeterAssocAndConfigType value) {
        this.waterMeterAssociation = value;
    }

}
