//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.08.27 at 11:59:11 PM EDT 
//


package com.es.manager.association;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * 
 *                     Indicates whether the whole facility energy consumption or only a portion of that total is represented by its meters. (Added 03/2011)
 *                 
 * 
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;all&gt;
 *         &lt;element name="propertyRepresentationType"&gt;
 *           &lt;simpleType&gt;
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string"&gt;
 *               &lt;enumeration value="Whole Property"/&gt;
 *               &lt;enumeration value="Common Area Energy Consumption Only"/&gt;
 *               &lt;enumeration value="Tenant Energy Consumption Only"/&gt;
 *               &lt;enumeration value="Combination of Tenant and Common Area Consumption"/&gt;
 *               &lt;enumeration value="Other"/&gt;
 *               &lt;enumeration value="No Selection Made"/&gt;
 *             &lt;/restriction&gt;
 *           &lt;/simpleType&gt;
 *         &lt;/element&gt;
 *         &lt;element name="tenantCommonAreaEnergyUseList" type="{}tenantCommonAreaEnergyUseInformationType" minOccurs="0"/&gt;
 *         &lt;element name="propertyRepresentationTypeOtherDesc" minOccurs="0"&gt;
 *           &lt;simpleType&gt;
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string"&gt;
 *               &lt;maxLength value="500"/&gt;
 *               &lt;minLength value="1"/&gt;
 *             &lt;/restriction&gt;
 *           &lt;/simpleType&gt;
 *         &lt;/element&gt;
 *       &lt;/all&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {

})
@XmlRootElement(name = "propertyRepresentation")
public class PropertyRepresentation {

    @XmlElement(required = true)
    protected String propertyRepresentationType;
    protected TenantCommonAreaEnergyUseInformationType tenantCommonAreaEnergyUseList;
    protected String propertyRepresentationTypeOtherDesc;
    
    public static enum Type {
    	WHOLE_PROPERTY("Whole Property"),
    	COMMON_AREA_ENERGY_CONSUMPTION("Common Area Energy Consumption Only"),
    	TENANT_ENERGY_CONSUMPTION("Tenant Energy Consumption Only"),
    	COMMON_AND_TENANT_ENERGY_CONSUMPTION("Combination of Tenant and Common Area Consumption"),
    	OTHER("Other"),
    	NONE("No Selection Made");		
    	private final String name;		
    	private Type(String name){
    		this.name = name;
    	}
    	
    	@Override
    	public String toString(){
    		return name;
    	}
    }
    
    /**
     * Gets the value of the propertyRepresentationType property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPropertyRepresentationType() {
        return propertyRepresentationType;
    }

    /**
     * Sets the value of the propertyRepresentationType property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPropertyRepresentationType(String value) {
        this.propertyRepresentationType = value;
    }

    /**
     * Gets the value of the tenantCommonAreaEnergyUseList property.
     * 
     * @return
     *     possible object is
     *     {@link TenantCommonAreaEnergyUseInformationType }
     *     
     */
    public TenantCommonAreaEnergyUseInformationType getTenantCommonAreaEnergyUseList() {
        return tenantCommonAreaEnergyUseList;
    }

    /**
     * Sets the value of the tenantCommonAreaEnergyUseList property.
     * 
     * @param value
     *     allowed object is
     *     {@link TenantCommonAreaEnergyUseInformationType }
     *     
     */
    public void setTenantCommonAreaEnergyUseList(TenantCommonAreaEnergyUseInformationType value) {
        this.tenantCommonAreaEnergyUseList = value;
    }

    /**
     * Gets the value of the propertyRepresentationTypeOtherDesc property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPropertyRepresentationTypeOtherDesc() {
        return propertyRepresentationTypeOtherDesc;
    }

    /**
     * Sets the value of the propertyRepresentationTypeOtherDesc property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPropertyRepresentationTypeOtherDesc(String value) {
        this.propertyRepresentationTypeOtherDesc = value;
    }

}
