//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.08.28 at 12:02:34 AM EDT 
//


package com.es.manager.property;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;

import com.es.manager.common.CustomFieldList;
import com.es.manager.common.LogType;
import com.es.manager.common.ShareLevelType;


/**
 * <p>Java class for pendingPropertiesType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="pendingPropertiesType"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="propertyId" type="{http://www.w3.org/2001/XMLSchema}long"/&gt;
 *         &lt;element ref="{}customFieldList" minOccurs="0"/&gt;
 *         &lt;element name="accessLevel" type="{}shareLevelType"/&gt;
 *         &lt;element name="accountId" type="{http://www.w3.org/2001/XMLSchema}long"/&gt;
 *         &lt;element name="propertyInfo" type="{}propertyType"/&gt;
 *         &lt;element name="shareAudit" type="{}logType" minOccurs="0"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "pendingPropertiesType", propOrder = {
    "propertyId",
    "customFieldList",
    "accessLevel",
    "accountId",
    "propertyInfo",
    "shareAudit"
})
public class PendingPropertiesType {

    protected long propertyId;
    protected CustomFieldList customFieldList;
    @XmlElement(required = true)
    @XmlSchemaType(name = "string")
    protected ShareLevelType accessLevel;
    protected long accountId;
    @XmlElement(required = true)
    protected PropertyType propertyInfo;
    protected LogType shareAudit;

    /**
     * Gets the value of the propertyId property.
     * 
     */
    public long getPropertyId() {
        return propertyId;
    }

    /**
     * Sets the value of the propertyId property.
     * 
     */
    public void setPropertyId(long value) {
        this.propertyId = value;
    }

    /**
     * Gets the value of the customFieldList property.
     * 
     * @return
     *     possible object is
     *     {@link CustomFieldList }
     *     
     */
    public CustomFieldList getCustomFieldList() {
        return customFieldList;
    }

    /**
     * Sets the value of the customFieldList property.
     * 
     * @param value
     *     allowed object is
     *     {@link CustomFieldList }
     *     
     */
    public void setCustomFieldList(CustomFieldList value) {
        this.customFieldList = value;
    }

    /**
     * Gets the value of the accessLevel property.
     * 
     * @return
     *     possible object is
     *     {@link ShareLevelType }
     *     
     */
    public ShareLevelType getAccessLevel() {
        return accessLevel;
    }

    /**
     * Sets the value of the accessLevel property.
     * 
     * @param value
     *     allowed object is
     *     {@link ShareLevelType }
     *     
     */
    public void setAccessLevel(ShareLevelType value) {
        this.accessLevel = value;
    }

    /**
     * Gets the value of the accountId property.
     * 
     */
    public long getAccountId() {
        return accountId;
    }

    /**
     * Sets the value of the accountId property.
     * 
     */
    public void setAccountId(long value) {
        this.accountId = value;
    }

    /**
     * Gets the value of the propertyInfo property.
     * 
     * @return
     *     possible object is
     *     {@link PropertyType }
     *     
     */
    public PropertyType getPropertyInfo() {
        return propertyInfo;
    }

    /**
     * Sets the value of the propertyInfo property.
     * 
     * @param value
     *     allowed object is
     *     {@link PropertyType }
     *     
     */
    public void setPropertyInfo(PropertyType value) {
        this.propertyInfo = value;
    }

    /**
     * Gets the value of the shareAudit property.
     * 
     * @return
     *     possible object is
     *     {@link LogType }
     *     
     */
    public LogType getShareAudit() {
        return shareAudit;
    }

    /**
     * Sets the value of the shareAudit property.
     * 
     * @param value
     *     allowed object is
     *     {@link LogType }
     *     
     */
    public void setShareAudit(LogType value) {
        this.shareAudit = value;
    }

}
