//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.08.28 at 12:02:34 AM EDT 
//


package com.es.manager.property.use;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.bind.annotation.XmlType;
import javax.xml.datatype.XMLGregorianCalendar;

import com.es.manager.common.LogType;
import com.es.manager.property.design.AmountOfLaundryProcessedAnnuallyType;
import com.es.manager.property.design.CoolingEquipmentRedundancyType;
import com.es.manager.property.design.ItEnergyConfigurationType;
import com.es.manager.property.design.MonthsInUseType;
import com.es.manager.property.design.MonthsSchoolInUseType;
import com.es.manager.property.design.NumberOfWeekdaysType;
import com.es.manager.property.design.OnsiteLaundryType;
import com.es.manager.property.design.OwnedByType;
import com.es.manager.property.design.PercentCooledType;
import com.es.manager.property.design.PercentHeatedType;
import com.es.manager.property.design.PercentOfficeCooledType;
import com.es.manager.property.design.PercentOfficeHeatedType;
import com.es.manager.property.design.PlantDesignFlowRateType;
import com.es.manager.property.design.PoolSizeType;
import com.es.manager.property.design.PoolType;
import com.es.manager.property.design.ResidentPopulationType;
import com.es.manager.property.design.UpsSystemRedundancyType;
import com.es.manager.property.design.FloorAreaTypeBase;
import com.es.manager.property.design.HoursPerDayGuestsOnsiteType;
import com.es.manager.property.design.LengthOfAllOpenClosedRefrigerationUnitsType;


/**
 * <p>Java class for useAttributeBase complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="useAttributeBase"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="audit" type="{}logType" minOccurs="0"/&gt;
 *       &lt;/sequence&gt;
 *       &lt;attribute name="id" type="{http://www.w3.org/2001/XMLSchema}long" /&gt;
 *       &lt;attribute name="currentAsOf" type="{http://www.w3.org/2001/XMLSchema}date" /&gt;
 *       &lt;attribute name="temporary" type="{http://www.w3.org/2001/XMLSchema}boolean" /&gt;
 *       &lt;attribute name="default"&gt;
 *         &lt;simpleType&gt;
 *           &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string"&gt;
 *             &lt;enumeration value="Yes"/&gt;
 *             &lt;enumeration value="No"/&gt;
 *             &lt;enumeration value="N/A"/&gt;
 *           &lt;/restriction&gt;
 *         &lt;/simpleType&gt;
 *       &lt;/attribute&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "useAttributeBase", propOrder = {
    "audit"
})
@XmlSeeAlso({
    UseYesNoType.class,
    UseStringType.class,
    UseDecimalType.class,
    UseIntegerType.class,
    PercentCooledType.class,
    PercentHeatedType.class,
    PercentOfficeCooledType.class,
    PercentOfficeHeatedType.class,
    MonthsInUseType.class,
    MonthsSchoolInUseType.class,
    PoolType.class,
    ResidentPopulationType.class,
    PoolSizeType.class,
    OwnedByType.class,
    CoolingEquipmentRedundancyType.class,
    UpsSystemRedundancyType.class,
    HoursPerDayGuestsOnsiteType.class,
    ItEnergyConfigurationType.class,
    OnsiteLaundryType.class,
    NumberOfWeekdaysType.class,
    AmountOfLaundryProcessedAnnuallyType.class,
    PlantDesignFlowRateType.class,
    LengthOfAllOpenClosedRefrigerationUnitsType.class,
    FloorAreaTypeBase.class
})
public abstract class UseAttributeBase {

    protected LogType audit;
    @XmlAttribute(name = "id")
    protected Long id;
    @XmlAttribute(name = "currentAsOf")
    @XmlSchemaType(name = "date")
    protected XMLGregorianCalendar currentAsOf;
    @XmlAttribute(name = "temporary")
    protected Boolean temporary;
    @XmlAttribute(name = "default")
    protected String _default;

    /**
     * Gets the value of the audit property.
     * 
     * @return
     *     possible object is
     *     {@link LogType }
     *     
     */
    public LogType getAudit() {
        return audit;
    }

    /**
     * Sets the value of the audit property.
     * 
     * @param value
     *     allowed object is
     *     {@link LogType }
     *     
     */
    public void setAudit(LogType value) {
        this.audit = value;
    }

    /**
     * Gets the value of the id property.
     * 
     * @return
     *     possible object is
     *     {@link Long }
     *     
     */
    public Long getId() {
        return id;
    }

    /**
     * Sets the value of the id property.
     * 
     * @param value
     *     allowed object is
     *     {@link Long }
     *     
     */
    public void setId(Long value) {
        this.id = value;
    }

    /**
     * Gets the value of the currentAsOf property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getCurrentAsOf() {
        return currentAsOf;
    }

    /**
     * Sets the value of the currentAsOf property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setCurrentAsOf(XMLGregorianCalendar value) {
        this.currentAsOf = value;
    }

    /**
     * Gets the value of the temporary property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isTemporary() {
        return temporary;
    }

    /**
     * Sets the value of the temporary property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setTemporary(Boolean value) {
        this.temporary = value;
    }

    /**
     * Gets the value of the default property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDefault() {
        return _default;
    }

    /**
     * Sets the value of the default property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDefault(String value) {
        this._default = value;
    }

}
